### ISSUE TITLE
Windows installation problem - file not found

### ISSUE THREAD

**Issue by jonatascoelho** [michele-segata/plexe-veins#23] opened 2021-06-17 19:28 UTC
Hello guys! I'm installing the plexe on windows 10, and after run "make", i got this error:

/c/User/plexe-plexe-3.0$ make
make[1]: Entering directory '/c/User/plexe-plexe-3.0/src'
plexe/apps/BaseApp.cc
plexe/apps/BaseApp.cc:25:10: fatal error: 'veins/modules/messages/BaseFrame1609_4_m.h' file not found
#include "veins/modules/messages/BaseFrame1609_4_m.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Makefile:228: ../out/clang-release/src/plexe/apps/BaseApp.o] Error 1

Inside the folder  "messages", there is no BaseFrame1609_4_m.h file.
I don't understood why this file wasn't created.

Can anyone help?

**Comment by michele-segata** [comment] 2021-06-18 06:49
`*_m.h` and `_m.cc` files are automatically generated by OMNeT++ from `*.msg` files when compiling a project. This suggests me that maybe you didn't compile Veins in the first place. Did you do so?

**Comment by jonatascoelho** [comment] 2021-06-21 18:48
Thanks for your attention, Michele!
I had forgotten to compile Veins.
But there's another problem, after run "make" on plexe, i got this:

/c/User/plexe-plexe-3.0$ make

make[1]: Entering directory '/c/User/plexe-plexe-3.0/src'
Creating shared library: ../out/clang-release/src/libplexe.dll
../out/clang-release/src/plexe/PlexeManager.o:(.text[_ZN5veins10FindModuleIPNS_20TraCIScenarioManagerEE13findSubModuleEPKN7omnetp         p7cModuleE]+0x2a): undefined reference to `typeinfo for veins::TraCIScenarioManager'
../out/clang-release/src/plexe/apps/BaseApp.o:(.rdata+0x840): undefined reference to `non-virtual thunk to veins::BaseModule::rec         eiveSignal(omnetpp::cComponent*, int, omnetpp::cObject*, omnetpp::cObject*)'
../out/clang-release/src/plexe/apps/BaseApp.o:(.rdata+0x8d0): undefined reference to `typeinfo for veins::BaseApplLayer'
../out/clang-release/src/plexe/apps/BaseApp.o:(.text[_ZN7omnetpp14check_and_castIPN5veins15BaseFrame1609_4ENS_8cMessageEEET_PT0_]         +0x1e): undefined reference to `typeinfo for veins::BaseFrame1609_4'
../out/clang-release/src/plexe/apps/BaseApp.o:(.text[_ZN5veins10FindModuleIPNS_13TraCIMobilityEE13findSubModuleEPKN7omnetpp7cModu         leE]+0x2a): undefined reference to `typeinfo for veins::TraCIMobility'
../out/clang-release/src/plexe/apps/BaseApp.o:(.rdata[_ZTIPN5veins15BaseFrame1609_4E]+0x18): undefined reference to `typeinfo for          veins::BaseFrame1609_4'

...

make[1]: *** [Makefile:218: ../out/clang-release/src/libplexe.dll] Error 1
make[1]: Leaving directory '/c/User/plexe-plexe-3.0/src'
make: *** [Makefile:38: all] Error 2

This appears to be a bug on windows 10 and in clang. How to solve this problem?

**Comment by michele-segata** [comment] 2021-06-25 06:21
I tried on a Windows 10 virtual machine. I opened the `mingwenv` terminal provided by OMNeT++, with which you already compiled OMNeT++ itself, cloned and compiled Veins, cloned and compiled Plexe. I cannot reproduce your problem. Did you use OMNeT++'s `mingwenv` terminal to compile Veins and Plexe?

**Comment by michele-segata** [comment] 2021-06-28 13:16
We tried investigating the issue and we found some problems both in Veins and in Plexe. This is going to be officially fixed in Veins release 5.2 and Plexe release 3.0.1. While you wait for the official release, you can fix the problem yourself.

W.r.t. Veins, you can fix the problem by simply replicating [this commit](https://github.com/sommer/veins/commit/f1de93125f1851dd2ac38a73e003fe17643b6755). After doing so, remember to re-compile Veins.

W.r.t. Plexe, the fix is in [this commit](https://github.com/michele-segata/plexe/commit/25ad76572a3d3ae30104fadeddef6720d8f88139). Again, re-compile Plexe after applying the changes.

After this, you should be able to run simulations both from the IDE and from the terminal. Please give us feedback on whether this works for you or not.

**Comment by Lenoral** [comment] 2021-07-12 15:53
Hi ! I also tried to install plexe on windows 10, I did what you recommanded, however I still got the errors :
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:218: ../out/clang-release/src/libplexe.dll] Error 1
make[1] : on quitte le répertoire « /c/Users/lil/src/plexe/src »
make: *** [Makefile:38: all] Error 2

Before that, here are some warnings for make veins if never it helps :
/c/Users/lil/src/veins$ make -j 6
Creating script "bin/veins_run"
make[1] : on entre dans le répertoire « /c/Users/lil/src/veins/src »
veins/visualizer/roads/RoadsCanvasVisualizer.cc
veins/visualizer/roads/RoadsOsgVisualizer.cc
In file included from veins/visualizer/roads/RoadsOsgVisualizer.cc:30:
In file included from .\veins/visualizer/roads/RoadsOsgVisualizer.h:29:
In file included from .\veins/veins.h:34:
In file included from C:/Users/lil/src/include\omnetpp.h:134:
In file included from C:/Users/lil/src/include/omnetpp/platdep/timeutil.h:41:
C:\Users\lil\src\tools\win64\mingw64\x86_64-w64-mingw32\include\winsock2.h:15:2:                                                                                                                                   warning: Please include winsock2.h before windows.h [-W#warnings]
#warning Please include winsock2.h before windows.h
 ^
1 warning generated.
Creating shared library: ../out/clang-release/src/libveins.dll
make[1] : on quitte le répertoire « /c/Users/lil/src/veins/src »
make[1] : on entre dans le répertoire « /c/Users/lil/src/veins/src »
veins/visualizer/roads/RoadsCanvasVisualizer.cc
veins/visualizer/roads/RoadsOsgVisualizer.cc
In file included from veins/visualizer/roads/RoadsOsgVisualizer.cc:30:
In file included from .\veins/visualizer/roads/RoadsOsgVisualizer.h:29:
In file included from .\veins/veins.h:34:
In file included from C:/Users/lil/src/include\omnetpp.h:134:
In file included from C:/Users/lil/src/include/omnetpp/platdep/timeutil.h:41:
C:\Users\lil\src\tools\win64\mingw64\x86_64-w64-mingw32\include\winsock2.h:15:2:                                                                                                                                   warning: Please include winsock2.h before windows.h [-W#warnings]
#warning Please include winsock2.h before windows.h
 ^
1 warning generated.
Creating shared library: ../out/clang-debug/src/libveins_dbg.dll

**Comment by jonatascoelho** [comment] 2021-07-12 17:38
Hi Michele, unfortunately there was no change in the error message after the updates you mentioned!
I decided to use the virtual machine that is available on the plexe website, this version has worked very well!
When release 5.2 and Plexe release 3.0.1 are available i will try again!

Thank you!

**Comment by michele-segata** [comment] 2022-01-10 08:56
Dear all,
I've tried the procedure above (by applying the patches to Veins and to Plexe) on a fresh install of Windows 10 and it worked at the first attempt for me. So I am going to close this issue. Feel free to re-open that if you have problems.

**Closed as completed by michele-segata** 2022-01-10 08:56 UTC
