### ISSUE TITLE
A runtime error occured: Error launching TraCI server

### ISSUE THREAD

**Issue by mateen-malik** [michele-segata/plexe-veins#17] opened 2021-01-09 22:59 UTC
![imgpsh_mobile_save](https://user-images.githubusercontent.com/74792496/104110326-03323380-52d7-11eb-8d06-668ca534e811.jpg)

When i tried to run any example of plexe-veins i got the following error. I see the file named "freeway.sumo.cfg" in my project.

**_<!> Error launching TraCI server ("sumo-gui --remote-port 50501 --seed 0 --configuration-file ./sumocfg/freeway.sumo.cfg"): the file is not found.
. Make sure you have set $PATH correctly. -- in module (Veins::TraCIScenarioManagerForker) Highway.manager (id=5), during network initialization_**

what is it i am doing wrong? Need your help

Thanks in advance,

Best regards,

**Comment by michele-segata** [comment] 2021-01-11 09:49
Can you launch SUMO from the terminal? Did you configure your PATH?

**Comment by mateen-malik** [comment] 2021-01-11 12:31
yes we can launch SUMO from the terminal (SUMO version 1.8.0).
The SUMO path is configured in the environment variables. 
![SUMOPATH](https://user-images.githubusercontent.com/74792496/104182140-47751f00-5410-11eb-8388-c5fe5f1f9523.JPG)

But still having the same error,

we we have done so far is as follows,

- We are running the plexe-veins (version 2.1) package inside OMNET++ (version 5.6.2) in Windows 10
- We have checked the TraCIScenarioManagerForker file but couldnt find anything related/specific to setting path.
- We have checked the file freeway.sumo.cfg file and couldnt find anything related/specific to setting path.

Is there anything else that we are missing?

**Comment by michele-segata** [comment] 2021-01-11 12:57
I was talking about the PATH environmental variable, but if you can run SUMO from the terminal it should be fine. You are using new versions of SUMO and OMNeT++ and an old version of Plexe. I would try using plexe-3.0a3 and Veins 5 or higher.

**Comment by mateen-malik** [comment] 2021-01-11 15:42
thanks for your guidance, 
now I have tried Veins 5.1 and plexe-3.0a3 and still getting the same error message :(

**Comment by michele-segata** [comment] 2021-01-11 16:48
Let's do a step back then. Are you able to run the [veins tutorial](http://veins.car2x.org/tutorial/) using the `veins_launchd` daemon instead of the `TraCIScenarioManagerForker`?

**Comment by mateen-malik** [comment] 2021-01-13 11:59
I am using OMNET++ IDE and have imported both "vein" and "plexe-veins" projects into the OMNET.
I could run veins examples from OMNET but couldnt run any plexe-veins example such as platooning etc. and get the error mentioned above everytime.

In order to run the sumo in the background i establish the port connection through this command in Ming
![Ming_sumo](https://user-images.githubusercontent.com/74792496/104449566-1545f780-559f-11eb-80c0-849b7a4a2b6b.JPG)

and i could also activate the sumo by using veins_launchd as well (see below)

![Ming_veins_launchd_1](https://user-images.githubusercontent.com/74792496/104450845-08c29e80-55a1-11eb-98ab-9f67c0dd6cf3.JPG)

**Comment by michele-segata** [comment] 2021-01-13 15:30
My suggestion is then to change the Plexe configuration to use the launchd instead of the forker.

**Comment by mateen-malik** [comment] 2021-01-13 15:32
How can i do that?
Sorry if i couldn't find it myself :(

**Comment by michele-segata** [comment] 2021-01-13 15:35
In issue #18 you are running a platooning example. This means Plexe is working. Why are you saying it doesn't? I'm a little confused.

**Comment by mateen-malik** [comment] 2021-01-13 15:37
Yeah the error is in my colleagues computer. In my computer i can run the simulation but we couldn't figure out what is the difference between his and my installations. So we are trying to solve the error instead which he is facing right now. 
sorry for any confusions

**Comment by mateen-malik** [comment] 2021-01-13 15:43
So how can i change the Plexe configuration to use the launchd instead of the forker?
Is there any guidance to do this?

**Comment by mateen-malik** [comment] 2021-01-13 15:47
We have tried to run the veins_launchd to execute sumo in the computer where we are getting the eror message and it executes as it should.

**Comment by michele-segata** [comment] 2021-01-13 19:28
So you did manage to run it?

**Comment by mehdi-maleki** [comment] 2021-01-14 07:36
Hi Michele, 
Thanks for your help.
The problem is in my computer, so far we did whatever you said but sadly could not mange to run it. 
Where I can change the plexe configuration to use the launchd?

**Comment by mehdi-maleki** [comment] 2021-01-14 07:38
Inside plexe-veins there is a configure file but seems that is not the correct place, do I need to change it inside Omnetpp?

**Comment by michele-segata** [comment] 2021-01-14 10:51
You have to modify `Highway.ned` to use the `launchd` scenario manager. Put `TraCIScenarioManagerLaunchd` instead of `TraCIScenarioManagerForker` [here](https://github.com/michele-segata/plexe-veins/blob/6d5f1edea95bf81b352962b99fb05751626cf024/examples/platooning/Highway.ned#L24) and [here](https://github.com/michele-segata/plexe-veins/blob/6d5f1edea95bf81b352962b99fb05751626cf024/examples/platooning/Highway.ned#L53). In the `sumocfg` folder create then a file named `freeway.launchd.xml` with the  following content:
```
<?xml version="1.0"?>
<launch>
    <basedir path="sumocfg" />
    <copy file="freeway.net.xml" />
    <copy file="freeway.rou.xml" />
    <copy file="freeway.gui.xml" />
    <copy file="freeway.sumo.cfg" type="config" />
</launch>
```

Start the `launchd` from the Plexe example folder you are running (change folders according to yours), e.g.,
```
cd ~/src/plexe-veins/examples/platooning
python ~/src/veins/sumo-launchd.py -c <PATH TO SUMO EXECUTABLE>
```
You can then run the simulation as usual and it should start.

**Comment by mehdi-maleki** [comment] 2021-01-14 13:47
Thanks for the feedback!

I did all the things you mentioned above, now it is opening the Qt page. When I try to run, it gives a different runtime error again which is related to the traci communication. I checked the listening port command errors, actually it closes the listening port immediately when I hit the run on Qt. The given errors attached below.
I'm trying to figure out what is the problem. Any suggestions are very appriciated.

Thanks for your help.
![image](https://user-images.githubusercontent.com/73038042/104597929-3a596980-5676-11eb-9db9-3f7134cd83d2.png)

![image](https://user-images.githubusercontent.com/73038042/104597671-e64e8500-5675-11eb-991d-c2791d35adce.png)

**Comment by michele-segata** [comment] 2021-01-14 13:49
It doesn't find SUMO configuration file. From which folder have you been launching the `sumo_launchd.py` script?

**Comment by mehdi-maleki** [comment] 2021-01-14 13:52
I tried both the platooning folder (cmd) and Omnetpp (from ming)

**Comment by mehdi-maleki** [comment] 2021-01-14 13:54
in platooning folder: python C:/omnetpp-5.6.2-src-windows/Dev/veins/sumo-launchd.py -vv -c C:/Users/mehdima/Downloads/sumo-win64-1.8.0/sumo-1.8.0/bin/sumo-gui.exe

**Comment by mehdi-maleki** [comment] 2021-01-14 13:56
It works

**Comment by mehdi-maleki** [comment] 2021-01-14 13:58
Thanks a lot. I was missing some letters in the command, just noticed when writing to you.

Thanks for your time and help!

**Comment by michele-segata** [comment] 2021-01-14 14:02
Great. Closing the issue.

**Closed as completed by michele-segata** 2021-01-14 14:02 UTC

**Comment by mateen-malik** [comment] 2021-01-14 14:04
Thanks alot for all your help and guidance

**Comment by hosseinihalimeh** [comment] 2024-10-23 06:50
> Hi Michele, Thanks for your help. The problem is in my computer, so far we did whatever you said but sadly could not mange to run it. Where I can change the plexe configuration to use the launchd?

سلام اقای ملکی وقتتون بخیر امکان داره من با شما ارتباط بگیرم در زمینه ‍plexeمن همین خطا رو دارم اما طیق صحبت ها جلو رفتم انجام نشد میشه به من کمک کنید

**Comment by michele-segata** [comment] 2024-10-23 11:30
> > Hi Michele, Thanks for your help. The problem is in my computer, so far we did whatever you said but sadly could not mange to run it. Where I can change the plexe configuration to use the launchd?
> 
> سلام اقای ملکی وقتتون بخیر امکان داره من با شما ارتباط بگیرم در زمینه ‍plexeمن همین خطا رو دارم اما طیق صحبت ها جلو رفتم انجام نشد میشه به من کمک کنید

@hosseinihalimeh Please enter your questions in English, otherwise it will simply be impossible for people to understand what your problem is about.
