### ISSUE TITLE
Strange vehicle behaviour

### ISSUE THREAD

**Issue by whatgit** [michele-segata/plexe-veins#6] opened 2019-03-11 09:37 UTC
![strange_sumo_behaviour](https://user-images.githubusercontent.com/4596256/54113275-34463200-43e8-11e9-9b7e-c7e7a9ab7928.jpg)

I was just trying to figure out what has happened in the simulation from an old logged data. I am wondering if anyone has experience such sudden change in speed before? According to the position, that vehicle (vehicle4) eventually collide with another vehicle after the sudden speed change (within a few second), I am just wondering if that is the indication that the vehicle has crashed in SUMO (then probably I should add that to the condition when detecting collision)

Unfortunately, this is not the log generated by Plexe so I do not have all parameters that are available there. The maximum speed allowed for those vehicles is 41 m/s (which is the value it jumps to)

I was using Plexe-2.0 (with plexe-sumo 0.26.0)

**Comment by michele-segata** [comment] 2019-03-13 07:10
Hi Maytheewat,
unfortunately it is difficult to understand why this happened without some contextual information. This jump in speed could really be caused by a crash, but it is just an educated guess. In any case, this is might have been related to a very old version of Plexe/Veins/SUMO.
I am closing this because I really cannot help you understanding what happened.

**Closed as completed by michele-segata** 2019-03-13 07:10 UTC

**Comment by whatgit** [comment] 2019-03-13 09:36
Thank you for your reply.

To give a context, it happens when another vehicle that is not connected changes lane and ends up between the platoon (by "not connected", I mean it does not have a node in Veins, but exist in SUMO)

Problem is that it does not consistently happen, it happens in about 15% of all experiments, and I have not found a condition to reproduce it yet. I will let you know if I see it again in the latest version of Plexe/Vein/SUMO.

**Comment by michele-segata** [comment] 2019-03-15 16:58
Well, this is a much more complicated problem to deal with. This never happened to me because I am using a very small intra-platoon distances, so "human" vehicles will never get into a platoon. If you are using larger spaces and human vehicles can get in then, as in the real world, there is the need to develop a high level protocol that detects anomalies and reacts to them, e.g., by splitting the platoon. These issues needs to be taken in consideration for the real world implementation.
